sudo: required
services:
  - docker

before_install:
  - docker build -t huriferenc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true huriferenc/react-test npm test -- --coverage

after_success:
  - docker build -t huriferenc/multi-client ./client
  - docker build -t huriferenc/multi-nginx ./nginx
  - docker build -t huriferenc/multi-server ./server
  - docker build -t huriferenc/multi-worker ./worker
  # Log in to the docker CLI
  # DOCKER_PASSWORD és DOCKER_ID környezeti változók, melyeket a Travis-ben adunk meg
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push huriferenc/multi-client
  - docker push huriferenc/multi-nginx
  - docker push huriferenc/multi-server
  - docker push huriferenc/multi-worker